apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: ${APP_NAME}
    team: ${TEAM_NAME}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: ${APP_NAME}
    team: ${TEAM_NAME}
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
        team: ${TEAM_NAME}
        version: ${VERSION}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9101"
    spec:
      serviceAccount: ${APP_NAME}
      containers:
      - name: ${APP_NAME}
        image: estafette/estafette-cloudflare-loadbalancer:${GO_PIPELINE_LABEL}
        imagePullPolicy: Always
        env:
        - name: "CF_API_EMAIL"
          value: "${CF_API_EMAIL}"
        - name: "CF_API_KEY"
          value: "${CF_API_KEY}"
        - name: "CF_ORG_ID"
          value: "${CF_ORG_ID}"
        - name: "CF_LB_NAME"
          value: "${CF_LB_NAME}"
        - name: "CF_LB_ZONE"
          value: "${CF_LB_ZONE}"
        - name: "CF_LB_POOL_NAME"
          value: "${CF_LB_POOL_NAME}"
        - name: "CF_LB_MONITOR_PATH"
          value: "${CF_LB_MONITOR_PATH}"
        - name: "CF_LB_TYPE"
          value: "${CF_LB_TYPE}"
        resources:
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9101
          initialDelaySeconds: 30
          timeoutSeconds: 1